##### STAGE 1 #####

FROM node:22.13.0 AS builder

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run swagger
RUN npm run prisma:generate && npm run build
RUN npm run copy-swagger

COPY fonts/ dist/fonts/
COPY img/ dist/img/

##### STAGE 2 #####

FROM node:22.13.0

WORKDIR /usr/src/app

RUN sed -i 's/^Components: main$/& contrib/' /etc/apt/sources.list.d/debian.sources
RUN apt-get update; apt-get install -y ttf-mscorefonts-installer fontconfig

COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/package.json ./package.json

EXPOSE 3005

CMD ["npm", "start"]