version: '3.8'
services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: meu_postgres
    environment:
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=1234
      - POSTGRESQL_DATABASE=pizzaplanet
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql
volumes:
  postgres_data:
    driver: local
