version: "3"

services: 
  app:
    image: DEV-JUANguillherme/PizzaPlanet.amd-64
    build: .
    container_name: PizzaPlanet
    restart: always
    tty: true
    networks: 
      - API-inspiratio-codeinnove_bridge
    ports: 
      - 9000:3000
      - 9229:9229
    volumes: 
      - .:/usr/src/app
      # - /usr/src/app/node_modules
    command: yarn start:dev
    environment:
      NODE_ENV: development
    depends_on: 
      - db

  db: 
    image: postgres:latest
    restart: always
    container_name: PizzaPlanet_postgres_db
    networks:
      - API-inspiratio-codeinnove_bridge
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pizza_planet_db
  networks:
  API-inspiratio-codeinnove_bridge:
    driver: bridge

volumes:
  postgres_data: # Volume nomeado para armazenar os dados do banco


