version: "3.8"

services:
  app:
    build: .
    container_name: PizzaPlanet
    restart: always
    tty: true
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/app
    command: yarn dev 
    # Ou `yarn start` se estiver em produção
    environment:
      NODE_ENV: development  # Ou production
      DATABASE_URL: postgres://root:root@db:5432/pizza_planet_db  # URL de conexão com o banco de dados
    depends_on:
      - db
    networks:
      - pizza_network

  db:
    image: postgres:latest
    container_name: PizzaPlanet_postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pizza_planet_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pizza_network

volumes:
  postgres_data:

networks:
  pizza_network: