version: "3"

services: 
  app:
    build: .
    container_name: PizzaPlanet
    restart: always
    tty: true
    ports: 
      - "9000:3000"
      - "9229:9229"
    volumes: 
      - .:/usr/src/app
    command: yarn start:dev
    environment:
      NODE_ENV: development
    depends_on: 
      - db
    networks:
      - pizza_network

  db: 
    image: postgres:latest
    restart: always
    container_name: PizzaPlanet_postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pizza_planet_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pizza_network

volumes:
  postgres_data:

networks:
  pizza_network: